### ISSUE TITLE
Question regarding those other Achievement tools

### ISSUE THREAD

**Issue by SudoHenk** [courtarro/fakeTube#1]
I believe there are also tools available with GUI to gain all the achievements you want via your own computer. Is it really nessecary to setup this server etc. meanwhile you also could just use one of those tools?

**Comment by courtarro** [comment]
Yeah, I'm aware of the other achievement cheats, but I feel like that ruins the game. I believe it also technically violates the Steam terms of service while this does not. It's fun working toward earning all the other achievements; I just made this tool because it's now literally impossible to earn the YouTube achievements legitimately. If someone wants to use that tool for just the YouTube achievements, I won't stop them. This is just another option.
